export const iconOptions = [
    { label: "JavaScript", value: "FaJs" },
    { label: "Java", value: "FaJava" },
    { label: "Python", value: "FaPython" },
    { label: "React", value: "FaReact" },
    { label: "Node.js", value: "FaNodeJs" },
    { label: "Bootstrap", value: "FaBootstrap" },
    { label: "CSS3", value: "FaCss3" },
    { label: "Git", value: "FaGitAlt" },
    { label: "Linux", value: "FaLinux" },
    { label: "Sass", value: "FaSass" },
    { label: "Terminal", value: "FaTerminal" },
    { label: "Markdown", value: "FaMarkdown" },
    { label: "Server", value: "FaServer" },
    { label: "Windows", value: "FaWindows" },
    { label: "Github", value: "FaGithub" },
    { label: "Code", value: "FaCode"},
    { label: "Typescript", value: "SiTypescript" },
    { label: "Mongodb", value: "SiMongodb" },
    { label: "Mysql", value: "SiMysql" },
    { label: "Firebase", value: "SiFirebase" },
    { label: "Django", value: "SiDjango" },
    { label: "Flask", value: "SiFlask" },
    { label: "Postman", value: "SiPostman" },
    { label: "Trello", value: "SiTrello" },
    { label: "Express", value: "SiExpress" },
    { label: "CodeBadge", value: "DiCodeBadge" },
    { label: "Html5", value: "DiHtml5" },
    { label: "Heroku", value: "DiHeroku" },
    { label: "Render", value: "SiRender" },
    { label: "Pandas", value: "SiPandas" },
    { label: "Matplotlib", value: "SiMatplotlib" },
    { label: "OpenAI / ChatGPT", value: "SiOpenai" },
    { label: "Claude", value: "SiClaude" },
    { label: "TensorFlow", value: "SiTensorflow" },
    { label: "PyTorch", value: "SiPytorch" },
    { label: "Machine Learning", value: "FaBrain" },
    { label: "Cybersecurity", value: "FaShieldAlt" },
    { label: "Data Science", value: "FaChartLine" },
]